### ISSUE TITLE
ATOM NUTS admin xml codes for all admins request

### ISSUE THREAD

**Issue by justinelliotmeyers** [rolfberkenbosch/meteoalert-api#11]
Reopening as it was closed without solving my request

@roaldnefs I meant the lower admin level warning areas - IE the NUTS3 level codes for all departments in France. Meteoalarms is starting to change the way codes are being deployed from their EMMA to some being EMMA, NUTS2, or NUTS3. please help before just closing to make sure it resolves my issue. Thanks!
Justin

**Comment by justinelliotmeyers** [comment]
ie 
![image](https://user-images.githubusercontent.com/5324316/69378335-2f769500-0c7c-11ea-8db1-4923088fe96e.png)

when you go into the page: https://www.meteoalarm.eu/ATOM/FR.xml

and look at individual feeds, you can see sections with:
		<area>
			<areaDesc>Seine Maritime</areaDesc>
			<geocode>
				<valueName>NUTS3</valueName>
				<value>FR232</value>
			</geocode>
		</area>
		<area>
			<areaDesc>Somme</areaDesc>
			<geocode>
				<valueName>NUTS3</valueName>
				<value>FR223</value>
			</geocode>

**Comment by justinelliotmeyers** [comment]
the only way I see to find a list of codes is when they actively have warnings. Do you know where I can find a full list of all EMMAID, NUTS2, and NUTS3 that they have/ warn for?

**Comment by rolfberkenbosch** [comment]
@justinelliotmeyers is this still a bug ? Otherwise i will close it.
