### ISSUE TITLE
Meteoalert hangs endlessly if meteoalarm.eu doesn't respond

### ISSUE THREAD

**Issue by pskowronek** [rolfberkenbosch/meteoalert-api#14]
Meteoalert hangs endlessly if meteoalarm.eu doesn't respond - this happened today, their site was not responding on time and meteoalarm lib hang (my whole clock suddenly stopped :)). There should be a reasonable timeout implemented while making a request to their server.

Now the site works so cannot provide steps to reproduce, probably the URL has to be change to something behind firewall silently blocking traffic.

This occurred on version 0.1.6, I guess I don't see any relevant changes in 0.1.7, so I think this issue still exists.

**Comment by rolfberkenbosch** [comment]
Sorry for my late response. Meteoalarm has finally update their api and moved to another domain. I hope it will be more responsive. For details check: https://github.com/home-assistant/core/pull/51383

**Comment by pskowronek** [comment]
The stability of their new API and/or domain/hosting is irrelevant, the main problem is still there - if something goes wrong on connection level, the library may hang endlessly. So, I wouldn't close this issue :)
