### ISSUE TITLE
Not matching province name when there are specific city names appended

### ISSUE THREAD

**Issue by prezervos** [rolfberkenbosch/meteoalert-api#22]
Hello,
could you implement some matching / regexp matching for the province name? In czechia feed [https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-czechia](url) you can find more entries with the same province name with additional information in brackets where are the names of specific cities in the province. At least for province "Středočeský kraj" there are more entries with different cities in brackets like in code below. With the possibility to use wildcards, there could be a province name like `"Středočeský kraj*Kladno*"` which would select a province matching this string.

> <entry>
    <cap:geocode>
      <valueName>EMMA_ID</valueName>
      <value>CZ009</value>
    </cap:geocode>
    <cap:areaDesc>Středočeský kraj (Brandýs nad Labem-Stará Boleslav, Český Brod, Kladno, Kolín, Kralupy nad Vltavou, Lysá nad Labem, Mělník, Mladá Boleslav, Mnichovo Hradiště, Neratovice, Nymburk, Poděbrady, Rakovník, Slaný)</cap:areaDesc>
    <cap:event>Flood Vigilance</cap:event>
    <cap:sent>2021-07-08T18:16:46+00:00</cap:sent>
    <cap:expires>2021-07-11T00:30:00+00:00</cap:expires>
    <cap:effective>2021-07-08T18:16:46+00:00</cap:effective>
    <cap:onset>2021-07-08T18:15:31+00:00</cap:onset>
    <cap:certainty>Likely</cap:certainty>
    <cap:severity>Moderate</cap:severity>
    <cap:urgency>Immediate</cap:urgency>
    <cap:scope>Public</cap:scope>
    <cap:message_type>Alert</cap:message_type>
    <cap:status>Actual</cap:status>
    <cap:identifier>2.49.0.0.203.0.CZ.210708181646.XOCZ55_OKSC_003425</cap:identifier>
    <link href="https://hub.meteoalarm.org/warnings/feeds-czechia/2caa4394-9e51-4ab8-9ba6-20d2b19c2bcc" type="application/cap+xml"/>
    <link href="https://meteoalarm.org?region=CZ" hreflang="en" rel="related" title="Czech Republic"/>
    <link href="https://meteoalarm.org?geocode=EMMA_ID:CZ009" hreflang="en" title="Středočeský kraj (Brandýs nad Labem-Stará Boleslav, Český Brod, Kladno, Kolín, Kralupy nad Vltavou, Lysá nad Labem, Mělník, Mladá Boleslav, Mnichovo Hradiště, Neratovice, Nymburk, Poděbrady, Rakovník, Slaný)"/>
    <author>
      <name>meteoalarm.org</name>
      <uri>https://meteoalarm.org</uri>
    </author>
    <published>2021-07-08T18:16:46Z</published>
    <id>https://hub.meteoalarm.org/warnings/feeds-czechia/2caa4394-9e51-4ab8-9ba6-20d2b19c2bcc?index_info=1&amp;index_area=0&amp;index_geocode=1</id>
    <title>Yellow Rain-flood Warning issued for Czech Republic - Středočeský kraj (Brandýs nad Labem-Stará Boleslav, Český Brod, Kladno, Kolín, Kralupy nad Vltavou, Lysá nad Labem, Mělník, Mladá Boleslav, Mnichovo Hradiště, Neratovice, Nymburk, Poděbrady, Rakovník, Slaný)</title>
    <updated>2021-07-08T18:16:46Z</updated>
  </entry>

> <entry>
    <cap:geocode>
      <valueName>EMMA_ID</valueName>
      <value>CZ009</value>
    </cap:geocode>
    <cap:areaDesc>Středočeský kraj (Beroun, Hořovice, Příbram)</cap:areaDesc>
    <cap:event>Very Strong Thunderstorms</cap:event>
    <cap:sent>2021-07-08T18:16:46+00:00</cap:sent>
    <cap:expires>2021-07-08T18:29:59+00:00</cap:expires>
    <cap:effective>2021-07-08T18:16:46+00:00</cap:effective>
    <cap:onset>2021-07-08T18:15:31+00:00</cap:onset>
    <cap:certainty>Observed</cap:certainty>
    <cap:severity>Severe</cap:severity>
    <cap:urgency>Immediate</cap:urgency>
    <cap:scope>Public</cap:scope>
    <cap:message_type>Alert</cap:message_type>
    <cap:status>Actual</cap:status>
    <cap:identifier>2.49.0.0.203.0.CZ.210708181646.XOCZ55_OKSC_003422</cap:identifier>
    <link href="https://hub.meteoalarm.org/warnings/feeds-czechia/e147e920-7569-4636-ad7c-32c2abb8a495" type="application/cap+xml"/>
    <link href="https://meteoalarm.org?region=CZ" hreflang="en" rel="related" title="Czech Republic"/>
    <link href="https://meteoalarm.org?geocode=EMMA_ID:CZ009" hreflang="en" title="Středočeský kraj (Beroun, Hořovice, Příbram)"/>
    <author>
      <name>meteoalarm.org</name>
      <uri>https://meteoalarm.org</uri>
    </author>
    <published>2021-07-08T18:16:46Z</published>
    <id>https://hub.meteoalarm.org/warnings/feeds-czechia/e147e920-7569-4636-ad7c-32c2abb8a495?index_info=1&amp;index_area=0&amp;index_geocode=1</id>
    <title>Orange Thunderstorm Warning issued for Czech Republic - Středočeský kraj (Beroun, Hořovice, Příbram)</title>
    <updated>2021-07-08T18:16:46Z</updated>
  </entry>

**Comment by SVH-Powel** [comment]
I agree with this. This is another example. Province is Vestfold and it will not match a warning like this:
<cap:areaDesc>Oestfold, Oslo, Akershus, Buskerud and Vestfold</cap:areaDesc>
In fact, the province has to be set to "Oestfold, Oslo, Akershus, Buskerud and Vestfold" to match and that is pointless.

Why not use 

<cap:geocode>
  <valueName>NUTS3</valueName>
  <value>NO033</value>
</cap:geocode>

instead of areaDesc?

**Comment by stigvi** [comment]
Here is another example. Oestafjells in not even a province in Norway.

`<cap:geocode>
      <valueName>NUTS3</valueName>
      <value>NO032</value>
    </cap:geocode>
    <cap:areaDesc>Oestafjells</cap:areaDesc>
    <cap:event>Frequent lightning</cap:event>`

There is no other solution to this than using the cap:geocode field.
