### ISSUE TITLE
Alert lookup is broken

### ISSUE THREAD

**Issue by attila123456** [rolfberkenbosch/meteoalert-api#27]
I haven't been getting alerts for some time and after some digging in the code, this part seems to be the root cause:

```python
            cap_url = None
            for link in entry.get('link'):
                if 'hub' in link.get('@href'):
                    cap_url = link.get('@href')
```

this is the `<link>` element in question:

```html
    <link href="https://feeds.meteoalarm.org/api/v1/warnings/feeds-netherlands/83495e3b-f9f9-4f3c-b3e3-b30b4449d1e3" type="application/cap+xml"/>
```

"hub" is nowhere in the href value. Perhaps searching for `type="application/cap+xml"` would be better?

**Comment by rolfberkenbosch** [comment]
Thanks for the commit, I just released a new version. Are you able to test it with your home-assistant ?

**Comment by rolfberkenbosch** [comment]
I have just test it @attila123456 and it worked. So i have update the package and also create a pull request @homeassistant. Hopefully it will be merged soon. Thanks again for your commit!
