### ISSUE TITLE
Atom feed doesn't include all the active alerts

### ISSUE THREAD

**Issue by oncleben31** [rolfberkenbosch/meteoalert-api#6]
Currently half of France is in alert. All the alerts are visible on the meteoalarm website but the atom feed has only a small part of them.

**Comment by rolfberkenbosch** [comment]
I will look if i can also fallback on rss when the xml feed doesn't have the information.

**Comment by yellowonblack** [comment]
I confirm the same issue for other EU countries. The website page is all the time up-to-date but not the atom feed.

**Comment by rolfberkenbosch** [comment]
Sorry for my late response. Meteoalarm has finally update their api. All countries support now the atom feed. That means that you can use for example germany now also. We have to wait when my pull request is merged in home-assistant. I think in the next release next month. For details check: https://github.com/home-assistant/core/pull/51383
