### ISSUE TITLE
Atom XML NUTS Codes Feed

### ISSUE THREAD

**Issue by justinelliotmeyers** [rolfberkenbosch/meteoalert-api#9]
it seems you can only find active warnings for a country in the xml feeds. The Meteoalarms newer style for warnings is based on NUTS codes for some countries, while others used the original style warning codes. 

Do you know where to find a complete list of codes for all countries?

Thank you,
Justin

**Comment by justinelliotmeyers** [comment]
@rolfberkenbosch could you help?  Thank you!

**Comment by roaldnefs** [comment]
@justinelliotmeyers, you can find an overview of all the available countries in the ATOM feed on https://www.meteoalarm.eu/ATOM/root.xml, e.g. the country code for the Netherlands is `NL`:

```xml
<...>
<entry>
<id>urn:oid:2.49.0.0.528.0</id>
<...>
<title>Netherlands</title>
<iso:countrycode>NL</iso:countrycode>
<...>
</entry>
<...>
```

**Comment by justinelliotmeyers** [comment]
@roaldnefs I meant the lower admin level warning areas - IE the NUTS3 level codes for all departments in France. Meteoalarms is starting to change the way codes are being deployed from their EMMA to some being EMMA, NUTS2, or NUTS3
